"use client";
import React from "react";
import type { Metadata } from "next";
import { client } from "../app/api/graphql/client";
import { Provider } from "urql";

import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const groteskBold = localFont({
    src: "./fonts/Grotesk/ClashGrotesk-Bold.woff",
    variable: "--font-grotesk-bold",
});

const groteskRegular = localFont({
    src: "./fonts/Grotesk/ClashGrotesk-Regular.woff",
    variable: "--font-grotesk-regular",
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Provider value={client}>
            <html lang="en">
                <body
                    className={`${groteskBold.variable} ${groteskRegular.variable} antialiased`}
                >
                    {children}
                </body>
            </html>
        </Provider>
    );
}
