type AuthPayload {
  token: String
  user: Users
}

type Clients {
  company_name: String
  country: String
  feedback_score: Float
  id: ID
  jobs: [Jobs!]
  total_spent: Float
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

type Jobs {
  budget: Float
  client_id: String
  clients: Clients
  created_at: DateTime
  description: String
  duration: String
  id: ID
  job_type: String
  rate: Float
  skills: [String!]
  title: String
  user_id: String
  users: Users
  workload: String
}

type Mutation {
  createUser(admin: Boolean, email: String!, full_name: String!, location: String, overview: String, password: String!, profile_url: String, rate: Float, reviews: [String!], skills: [String!], title: String!): Users
  login(email: String!, password: String!): AuthPayload
  signup(email: String!, full_name: String!, password: String!, title: String!): SignupPayload
}

"""The query root type."""
type Query {
  jobByID(id: String!): Jobs
  user(id: ID!): sati_users
  userByEmail(email: String!): Users
}

type SignupPayload {
  success: Boolean
  token: String
  user: Users
}

input UserUniqueInput {
  email: String
}

type Users {
  admin: Boolean
  email: String
  full_name: String
  id: ID
  jobs: [Jobs!]
  overview: String
  profile_url: String
  rate: Float
  reviews: [String!]
  skills: [String!]
  title: String
}

type loginPayload {
  user: Users
}

type sati_users {
  email: String
  id: ID
  password: String
}